#!/usr/bin/env python3 

import minio
import json
import time
import os

if __name__ == '__main__':
    target_file_name = str(int(time.time()))
    j = json.load(open('/home/jay/Desktop/credentials.json','rb'))
    c = minio.Minio(j.get('url'), access_key=j.get('accessKey'), secret_key=j.get('secretKey'),secure=False)
    f = open('main.py', 'rb')
    f.seek(0, os.SEEK_END)
    length = f.tell()
    for v in range(30):
        f.seek(0, os.SEEK_SET)
        c.fput_object('default', target_file_name, open('main.py','rb'), length)
    c.close()
    f.close()
